GET http://localhost:4000/activity/2/entry
Authorization: Bearer <token>

###

POST http://localhost:4000/activity/2/entry
Authorization: Bearer <token>
Content-Type: application/json

{
    "startAt": "2025-10-25T15:29:24.164Z",
    "finishAt": "2025-10-25T16:29:24.164Z"
}

###

GET http://localhost:4000/activity/2/entry/3
Authorization: Bearer <token>

###

PATCH http://localhost:4000/activity/2/entry/3
Authorization: Bearer <token>
Content-Type: application/json

{
    "startAt": "2025-10-25T15:29:24.164Z",
    "finishAt": "2025-10-25T16:29:24.164Z"
}

###

DELETE  http://localhost:4000/activity/2/entry/3
Authorization: Bearer <token>
