POST http://localhost:4000/auth/sign-up
Authorization: Bearer <token>
Content-Type: application/json

{
    "name": "ian",
    "email": "iansandoval264@gmail.com",
    "password": "********"
}

###

POST http://localhost:4000/auth/sign-in
Authorization: Bearer <token>
Content-Type: application/json

{
    "email": "iansandoval264@gmail.com",
    "password": "********"
}

###

POST http://localhost:4000/auth/sign-out
Authorization: Bearer <token>
