GET http://localhost:4000/section
Authorization: Bearer <token>

###

POST http://localhost:4000/section
Authorization: Bearer <token>
Content-Type: application/json

{
    "name": "F5",
    "year": 2
}

###

GET http://localhost:4000/section/2
Authorization: Bearer <token>

###

PATCH http://localhost:4000/section/2
Authorization: Bearer <token>
Content-Type: application/json

{
    "name": "F4",
    "year": 4
}

###

DELETE  http://localhost:4000/section/2
Authorization: Bearer <token>
