POST http://localhost:4000/esp/event/1/attendance
Authorization: Bearer <token>
Content-Type: application/json

{
    "rfid": "12093"
}

###

DELETE http://localhost:4000/esp/event/1/attendance/12369
Authorization: Bearer <token>